### ISSUE TITLE
example video file to test with?

### ISSUE THREAD

**Issue by andrewarrow** [FyshOS/movies#1]
Great job with this repo! This is a working fyne video player. If you have been watching https://github.com/fyne-io/fyne/issues/449 they used to say this wasn't possible.

I've been testing it with various video files and some play better than others. Often the video images are blurry and off center but the audio is perfect. Do you have an example video file that plays perfectly?

**Comment by andydotxyz** [comment]
The one shown in README is this, a sting from FyneConf videos.

https://user-images.githubusercontent.com/294436/174652736-733bae60-05f9-413f-ae84-999f5a7aebfc.mp4
