### ISSUE TITLE
Can we use Go arena?

### ISSUE THREAD

**Issue by dharanict** [FyshOS/movies#2]
This is just an enhancement request.

Go has arena support now:
https://github.com/golang/go/issues/51317
https://www.reddit.com/r/golang/comments/sys1pr/proposal_arena_new_package_providing_memory_arenas/

I am just wondering if using arena would help improve performance. Please do the needful.

Please ignore if this is not relevant or needed.

Note: I have raised a similar request for reisen here: https://github.com/zergon321/reisen/issues/16

**Comment by andydotxyz** [comment]
How would using that new feature help the memory usage of an image buffer such as this?

> Please do the needful.

I don't know what this means, sorry.

**Comment by Jacalz** [comment]
Just shoving the `arena` package into every Go project seems no better to me than to to rewrite every software project in Rust. It is not a perfect solution to all memory management issues and is not suitable in every situation. Considering that the package is experimental and was removed from the Go 1.20 release as they were unsure about it, I think we should reconsider this once it (if ever) removes it's experimental status.

**Comment by dharanict** [comment]
Thanks for the details.
